### ISSUE TITLE
make proxy detection optional, toggle able

### ISSUE THREAD

**Issue by jxsl13** [jxsl13/TeeworldsEconVPNDetection#5]
chillerdraghuhn:
```
i mean home servers are a thing so it might have false positives by default
```

**Comment by ChillerDragon** [comment]
Imo even turned on it could try to reduce false positives. If one sets up a test server using the default name "unnamed server" it is likley not a malicious proxy server trying to steal data.

Another idea is to only flag those servers as proxy that duplicate an existing server by same player count or same name (should probably also detect confusable names).

**Comment by jxsl13** [comment]
I wonder how many IPs overlap when fetching the teeworlds 0.7 server list vs the ddnet http master server. fetching the individual server information for every ip returned by the master server is a pain in the butt :D

**Comment by jxsl13** [comment]
in fact, the http json master servers contains all 0.6 and all 0.7 servers, making the usage of my twapi library obsolete.

**Comment by jxsl13** [comment]
this allows for some nice improvements in this issue

**Comment by jxsl13** [comment]
dc3e1c99ce6f44a7a82ba30a8f7f4bba57af1b36
implements this server name distance check which decreases the list of cached IPs from like 200 to anything you like.
the current default value `8` decreases the list of servers similar to my zCatch/gCTF servers from 200 to 3 IPs and 5 servers.
